### ISSUE TITLE
Running via Leiningen 2 doesn't return proper exit code

### ISSUE THREAD

**Issue by r0man** [pallet/pallet-lein#6]
If an error happens during deployment "lein pallet" doesn't
return the proper exit code. Instead of returning numbers,
Leiningen 2 plugins should call leiningen.core.main/abort or
leiningen.core.main/exit as described over here:

https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#upgrading-existing-plugins

**Comment by hugoduncan** [comment]
Should be fixed, shout if not.
